version: "3.1" # needed for mongo 4
services:
  mongo1:
    container_name: $MONGO_HOST
    image: mongo:4 # needed for version 3.1
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      # - PUID=1000
      # - PGID=1000
      - MONGO_INITDB_DATABASE=admin # Needed to authenticate
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    volumes:
      - ./db:/data/db
      - ./init-mongo-js.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    command: ['--auth', '--wiredTigerCacheSizeGB=1']
    restart: unless-stopped

    networks:
      - mongo-network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_PASS
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=$MONGO_HOST
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASS
    depends_on:
      - $MONGO_HOST
    networks:
      - mongo-network
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge
