version: "3.1" # needed for mongo 4
services:
  mongo1:
    container_name: ${MONGO_HOST}
    image: mongo:4 # needed for version 3.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./db:/data/db
    restart: unless-stopped
    networks:
      - mongo-network
  mongo-express:
    # build:
    #   context: ./mongoexpress/
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}

      - ENV_MONGO_USER=${MONGO_USER}
      - ENV_MONGO_PASS=${MONGO_PASS}

    depends_on:
      - ${MONGO_HOST}
    networks:
      - mongo-network
    # command: ["./wait-for-it.sh", "mongodb://${MONGO_USER}${':'}${MONGO_PASS}@mongo1${':'}27017/admin"]
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge
