version: "3.1" # needed for mongo 4
services:
  mongo1:
    container_name: ${MONGO_HOST}
    image: mongo:4 # needed for version 3.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}

      # Need for init-mongo-js.sh
      - MONGO_COLLECTION=${MONGO_COLLECTION}

    volumes:
      - volume-mongo:/data/db
      # Needed permissions for specific user - MONGO_USER
      - ./init-mongo-js.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

    restart: unless-stopped
    networks:
      - mongo-network

  node-import:
    container_name: node-import
    build: 
      context: ./node-import-csv
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_DB=$MONGO_DB
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_PORT=$MONGO_PORT
      - MONGO_COLLECTION=$MONGO_COLLECTION

      # While MONGO_HOST and MONGO_PORT is supplied above, 
      # better to keep generic wait.sh file for other usecase and supply 
      # specific name  WAIT_HOST and WAIT_PORT here...
      - WAIT_HOST=$MONGO_HOST
      - WAIT_PORT=$MONGO_PORT
    ports:
      - 8000:8000
    depends_on:
    - ${MONGO_HOST}
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
    depends_on:
      - ${MONGO_HOST}
    networks:
      - mongo-network
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge
