version: "3.1" # needed for mongo 4
services:
  mongo1:
    container_name: ${MONGO_HOST}
    image: mongo:4 # needed for version 3.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./db:/data/db
      - ./init-mongo-js.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped
    networks:
      - mongo-network

  dbseed: # Create separate service to import into mongo after mongo is loaded up.
    container_name: dbseed
    build:
      context: .
      args: # Needed for import csv - CMD
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - MONGO_TABLE_COLLECTION_NAME=${MONGO_TABLE_COLLECTION_NAME}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
    depends_on:
    - ${MONGO_HOST}
    networks:
      - mongo-network
      
    restart: unless-stopped
  mongo-express:

    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}

      # Needed for import csv - CMD
      # - ENV_MONGO_DB_NAME=${MONGO_DB_NAME}
      # - ENV_MONGO_TABLE_COLLECTION_NAME=${MONGO_TABLE_COLLECTION_NAME}
    depends_on:
      - ${MONGO_HOST}
    networks:
      - mongo-network
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge
