import React from "react";
import Head from "next/head";

const MasterHead = () => (
  <Head>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <meta charSet="utf-8" />
    <meta httpEquiv="X-Ua-Compatible" content="IE=Edge" />
    <meta name="robots" content="index, follow" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1.0"
    />
  </Head>
);

export default MasterHead;
